/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dota.sound.editor;

import info.ata4.vpk.VPKArchive;
import info.ata4.vpk.VPKEntry;
import java.awt.event.ItemEvent;
import java.io.*;
import java.nio.channels.FileChannel;
import java.nio.file.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Set;
import java.util.concurrent.CopyOnWriteArraySet;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;
import static java.nio.file.StandardCopyOption.*;
import java.util.Enumeration;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author Image 17
 */
public class SoundEditorMainForm extends javax.swing.JFrame
{

    /**
     * Creates new form SoundEditorMainForm
     */
    String fileName;
    String installDir;
    PortraitFinder portraitFinder;

    public SoundEditorMainForm(String _fileName, String _installDir)
    {
        fileName = _fileName;
        installDir = _installDir;
        portraitFinder = new PortraitFinder(fileName);
        initComponents();
        jMenuBar1.setVisible(false);        
        populateDropdownBox();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        heroDropdown = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        heroImageLabel = new javax.swing.JLabel();
        replaceButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lengthField = new javax.swing.JTextField();
        frequencyField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        channelsField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        exportButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dota 2 Sound Editor");
        setMinimumSize(new java.awt.Dimension(353, 485));
        setPreferredSize(new java.awt.Dimension(353, 485));

        heroDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        heroDropdown.setName("heroDropdownBox"); // NOI18N
        heroDropdown.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                heroDropdownStateChanged(evt);
            }
        });

        jLabel1.setText("Hero:");
        jLabel1.setName("heroLabel"); // NOI18N

        jScrollPane1.setName("heroListFrame"); // NOI18N

        jTree1.setPreferredSize(new java.awt.Dimension(323, 64));
        jScrollPane1.setViewportView(jTree1);

        heroImageLabel.setMaximumSize(new java.awt.Dimension(128, 72));
        heroImageLabel.setMinimumSize(new java.awt.Dimension(128, 72));
        heroImageLabel.setPreferredSize(new java.awt.Dimension(128, 72));

        replaceButton.setText("Replace");
        replaceButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                replaceButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lengthField.setText("Length:");
        lengthField.setBorder(null);
        lengthField.setFocusable(false);
        lengthField.setOpaque(false);

        frequencyField.setText("441000 Hz");
        frequencyField.setBorder(null);
        frequencyField.setFocusable(false);
        frequencyField.setOpaque(false);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        channelsField.setText("Stereo");
        channelsField.setBorder(null);
        channelsField.setFocusable(false);
        channelsField.setOpaque(false);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(frequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(channelsField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(204, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(194, 194, 194)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(frequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(channelsField, javax.swing.GroupLayout.Alignment.LEADING))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        exportButton.setText("Create Tree");
        exportButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exportButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");

        jMenuItem4.setText("Change install directory");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem2.setText("How to use");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);
        jMenu3.add(jSeparator7);

        jMenuItem3.setText("About");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heroDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heroImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 176, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 175, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(176, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heroDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(heroImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(replaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 232, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 232, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(227, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void heroDropdownStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_heroDropdownStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            System.out.println(heroDropdown.getSelectedItem().toString());
            //populateSoundList((NamedHero) heroDropdown.getSelectedItem());
            populateSoundListAsTree((NamedHero)heroDropdown.getSelectedItem());
            jTree1.setRootVisible(false);
            jTree1.setShowsRootHandles(true);
            try
            {
                fillImageFrame((NamedHero) heroDropdown.getSelectedItem());
            }
            catch (IOException ex)
            {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_heroDropdownStateChanged

    private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
        if (jTree1.getSelectionRows() != null && 
                ((TreeNode)jTree1.getSelectionPath().getLastPathComponent()).isLeaf())
        {
            TreeNode selectedFile = ((TreeNode)jTree1.getSelectionPath().getLastPathComponent());                       

            //See if they have an autoexec.cfg
            String autoExecPath = checkForAutoExec();
            if (autoExecPath != null)
            {
                //Make sure snd_overridecache is set
                checkAndSetSndUpdate(autoExecPath);
            }
            else    //Otherwise, create autoexec.cfg and set snd_updatecache
            {
                autoExecPath = createAutoExecCfg();
                checkAndSetSndUpdate(autoExecPath);
            }                        

            //Prompt user to pick a file to replace with
            File newSoundFile = promptUserForNewFile(selectedFile.toString());           
            //Check for file type sameness, *OPTIONAL* check for sound-length, stereo-ness and frequency matching
            //Copy file into relevant folder, rename it as necessary. See code below in PopulateSoundList to see how to get the sound file's filepath
        }
    }//GEN-LAST:event_replaceButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exportButtonActionPerformed
    {//GEN-HEADEREND:event_exportButtonActionPerformed
        //TODO:
        // Abstract this into its own function
        // Rename it to be the "Advanced" or "Details" button
        //This is going to turn into the "Advanced" view, later
        VPKEntry scriptFile = getHeroScriptFile(((NamedHero) heroDropdown.getSelectedItem()).getInternalName());
        ScriptParser parser = new ScriptParser(new File(Paths.get(installDir + "\\dota\\" + scriptFile.getPath()).toString()));
        TreeModel model = parser.getTreeModel();
        jTree1.setModel(model);
    }//GEN-LAST:event_exportButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void populateDropdownBox()
    {
        heroDropdown.removeAllItems();
        Set heroList = new CopyOnWriteArraySet();
        //Build list of heroes and populate dropwdown with it                
        File file = new File(fileName);
        VPKArchive vpk = new VPKArchive();

        System.out.println(file);

        try
        {
            vpk.load(file);
        }
        catch (Exception ex)
        {
            System.err.println("Can't open archive: " + ex.getMessage());
            return;
        }


        for (VPKEntry entry : vpk.getEntries())
        {
            if (entry.getPath().contains("scripts/game_sounds_heroes/"))
            {
                if (vpk.isMultiChunk())
                {
                    //System.out.printf("%s:%s\n", entry.getFile().getName(), entry.getPath());
                }
                else
                {
                    //System.out.println(entry.getPath());
                }
                heroList.add(entry.getName());
            }
        }

        //@TODO: Come back to this to format it properly and replace hero names
        //with correct names

        //Format and prettify hero list
        for (Object hero : heroList)
        {
            String heroString = hero.toString();
            heroString = heroString.replace("game_sounds_", "");
            NamedHero tempNamedHero = new NamedHero(heroString);
            heroList.remove(hero);
            heroList.add(tempNamedHero);
        }
        Object[] heroListArray = heroList.toArray();
        Arrays.sort(heroListArray);
        for (Object h : heroListArray)
        {
            NamedHero tempHero = (NamedHero) h;
            heroDropdown.addItem(tempHero);
        }

        //populateSoundList((NamedHero) heroDropdown.getSelectedItem());
        populateSoundListAsTree((NamedHero)heroDropdown.getSelectedItem());
    }

    //TODO: Look into deprecating this method and its associated jList.
//    private void populateSoundList(NamedHero selectedHero)
//    {
//        this.getHeroScriptFile(selectedHero.internalName);
//        Path scriptPath = Paths.get(this.installDir + "\\dota\\scripts\\game_sounds_heroes\\game_sounds_" + selectedHero.getInternalName() + ".txt");
//        ScriptParser parser = new ScriptParser(scriptPath.toFile());
//        TreeModel scriptTree = parser.getTreeModel();
//        DefaultListModel scriptList = new DefaultListModel();
//
//        //Get all children of root node:
//        TreeNode rootNode = (TreeNode) scriptTree.getRoot();
//        int childCount = rootNode.getChildCount();
//        for (int i = 0; i < childCount; i++)
//        {
//            scriptList.addElement(scriptTree.getChild(rootNode, i));
//        }
//
//        heroSoundList.setModel(scriptList);
//    }
    
    private void populateSoundListAsTree(NamedHero selectedHero)
    {
        this.getHeroScriptFile(selectedHero.internalName);
        Path scriptPath = Paths.get(this.installDir + "\\dota\\scripts\\game_sounds_heroes\\game_sounds_" + selectedHero.getInternalName() + ".txt");
        ScriptParser parser = new ScriptParser(scriptPath.toFile());
        TreeModel scriptTree = parser.getTreeModel();
        DefaultListModel scriptList = new DefaultListModel();
        TreeNode rootNode = (TreeNode) scriptTree.getRoot();
        int childCount = rootNode.getChildCount();
        
        TreeModel soundListTreeModel = new DefaultTreeModel(new DefaultMutableTreeNode("root"));
        ArrayList<String> wavePathsList = new ArrayList<String>();
        for(int i = 0; i < childCount; i++)
        {
            
             wavePathsList = this.getWavePathsAsList((TreeNode)scriptTree.getChild(rootNode, i));
             String nodeValue = scriptTree.getChild(rootNode, i).toString();
             DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(nodeValue);
             
             for(String s : wavePathsList)
             {
                 DefaultMutableTreeNode tempNode = new DefaultMutableTreeNode(s);
                 newNode.add(tempNode);
             }
             ((DefaultMutableTreeNode)soundListTreeModel.getRoot()).add(newNode);
        }
        
        jTree1.setModel(soundListTreeModel);                 
    }

    //Just an example for now
    private void fillImageFrame(NamedHero selectedItem) throws IOException
    {
        try
        {
            heroImageLabel.setIcon(new ImageIcon(portraitFinder.getPortrait(selectedItem.internalName)));
        }
        catch (NullPointerException ex)
        {
            System.err.println("Icon not found.");
            heroImageLabel.setIcon(new ImageIcon(""));
        }
    }

    public static int nthOccurrence(String str, char c, int n)
    {
        int pos = str.indexOf(c, 0);
        while (n-- > 0 && pos != -1)
        {
            pos = str.indexOf(c, pos + 1);
        }
        return pos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField channelsField;
    private javax.swing.JButton exportButton;
    private javax.swing.JTextField frequencyField;
    private javax.swing.JComboBox heroDropdown;
    private javax.swing.JLabel heroImageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextField lengthField;
    private javax.swing.JButton replaceButton;
    // End of variables declaration//GEN-END:variables

    private String checkForAutoExec()
    {
        Path autoExecPath = Paths.get(installDir + "//dota//cfg//autoexec.cfg");
        File autoExecFile = new File(autoExecPath.toString());
        File[] fileList = autoExecFile.getParentFile().listFiles();

        for (File f : fileList)
        {
            if (f.getAbsolutePath().equalsIgnoreCase(autoExecFile.getAbsolutePath()))
            {
                return f.getAbsolutePath();
            }
        }
        return null;
    }

    //Reads autoexec.cfg for the snd_updateaudiocache line. Adds it if nonexistent.
    private void checkAndSetSndUpdate(String autoExecPath)
    {
        InputStream fis;
        BufferedReader br;

        FileWriter fos;
        BufferedWriter bw;
        String line;

        try
        {
            fis = new FileInputStream(autoExecPath);
            br = new BufferedReader(new InputStreamReader(fis));

            while ((line = br.readLine()) != null)
            {
                if (line.contains("snd_updateaudiocache"))
                {
                    return;
                }
            }
            br.close();

            //If the line doesn't exist, append it to to the file
            fos = new FileWriter(autoExecPath, true);
            bw = new BufferedWriter(fos);
            bw.write(System.lineSeparator() + "snd_updateaudiocache");
            bw.close();
        }
        catch (Exception ex)
        {
            System.err.println(ex);
            //TODO: bail out or inform the user what went wrong. This one's important, and they might be able to fix it manually.
        }
    }

    private String createAutoExecCfg()
    {
        Path autoExecPath = Paths.get(installDir + "//dota//cfg//");
        File autoExecFile = new File(autoExecPath.toString(), "autoexec.cfg");
        autoExecFile.getParentFile().mkdirs();
        try
        {
            autoExecFile.createNewFile();
        }
        catch (Exception ex)
        {
            System.err.println(ex);
        }
        return autoExecFile.getAbsolutePath();
    }

    //TODO: Rewrite this to not write to disk unless we're actually making changes.
    private VPKEntry getHeroScriptFile(String heroName)
    {
        //String massaging to get the hero name from the filepath. Remove underscores because underscore use in game files for hero names is inconsistent.        
        heroName = heroName.toLowerCase();

        //Block for special cases here. Known special cases: Bristleback/Bristlebog
        if (heroName.equals("Bristleback"))
        {
            heroName = "Bristlebog";
        }

        //Don't bother looking if we already have a stored copy locally.
        File existsChecker = new File(Paths.get(installDir + "\\dota\\scripts\\game_sounds_heroes\\game_sounds_" + heroName + ".txt").toString());
        boolean fileExistsLocally = false;
        if (existsChecker.exists())
        {
            fileExistsLocally = true;
        }
        File file = new File(fileName);
        VPKArchive vpk = new VPKArchive();

        try
        {
            vpk.load(file);
        }
        catch (Exception ex)
        {
            System.err.println("Can't open archive: " + ex.getMessage());
            return null;
        }

        Path destPath = Paths.get(installDir + "\\dota\\");
        File destDir = destPath.toFile();

        for (VPKEntry entry : vpk.getEntries())
        {
            if (entry.getName().contains("game_sounds_" + heroName))
            {
                //If it already exists, break out and move on.
                if(fileExistsLocally)
                {
                    return entry;
                }
                
                File entryFile = new File(destDir, entry.getPath());

                File entryDir = entryFile.getParentFile();
                if (entryDir != null && !entryDir.exists())
                {
                    entryDir.mkdirs();
                }

                try (FileChannel fc = FileUtils.openOutputStream(entryFile).getChannel())
                {
                    fc.write(entry.getData());
                    //System.out.println("Writing " + heroName +"'s game sounds file out.");
                    return entry;
                }
                catch (IOException ex)
                {
                    System.err.println("Can't write " + entry.getPath() + ": " + ex.getMessage());
                }
            }
        }
        return null;
    }

    private File promptUserForNewFile(String wavePath)
    {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MP3s and WAVs", "mp3", "wav");
        chooser.setFileFilter(filter);

        //TODO: Change this following block so that:                
        //      - The TreeNode's wave property is changed
        //      - The modified tree gets written to a new script file
        //      - The new script file gets written to disk and replaces the exisiting one
        //      - The UI bits all update                
        int chooserRetVal = chooser.showOpenDialog(chooser);
        if (chooserRetVal == JFileChooser.APPROVE_OPTION)
        {
            TreeNode selectedFile = getTreeNodeFromWavePath(wavePath);
            
            Path chosenFile = Paths.get(chooser.getSelectedFile().getAbsolutePath());
            
            //TODO: REVISIT this line (and whole block) and check it for sanity
            ArrayList wavePathsList = getWavePathsAsList(selectedFile);
            
            //RECHECK THIS STATEMENT
            Path destPath = Paths.get(installDir + "\\dota\\customsounds\\" +
                    ((NamedHero)heroDropdown.getSelectedItem()).getInternalName()
                    + "\\" + chosenFile.getFileName());

            try
            {
                boolean success = new File(destPath.toString()).mkdirs();
                Files.copy(chosenFile, destPath, REPLACE_EXISTING);
                JOptionPane.showMessageDialog(this, "Sound file successfully replaced.");
            }
            catch (IOException ex)
            {
                System.err.println(ex);
            }
        }
        return null;
    }

    //TODO: Definitely come back to this later. SUPER hacky implementation right now.
    private void setSoundText(VPKEntry soundFileEntry)
    {
        if (soundFileEntry != null)
        {
            File entryFile = new File(Paths.get("scratch.wav").toString());
            try (FileChannel fc = FileUtils.openOutputStream(entryFile).getChannel())
            {
                fc.write(soundFileEntry.getData());
                fc.close();
            }
            catch (IOException ex)
            {
                System.err.println("Can't write " + soundFileEntry.getPath() + ": " + ex.getMessage());
            }

            AudioFormat format = null;
            try
            {
                AudioInputStream audioIn = AudioSystem.getAudioInputStream(entryFile);
                format = audioIn.getFormat();
            }
            catch (Exception ex)
            {
                System.err.println(ex.getMessage());
            }

            //Duration box
            if (format != null)
            {
                long audioFileLength = entryFile.length();
                int frameSize = format.getFrameSize();
                float frameRate = format.getFrameRate();
                float s = (audioFileLength / (frameSize * frameRate));
                String duration = String.format("%.2f", s);
                lengthField.setText("Length: " + duration + "s");

                frequencyField.setText(Float.toString(format.getSampleRate()) + " Hz");

                String channelsText = (format.getChannels() == 2) ? "Stereo" : "Mono";

                channelsField.setText(channelsText);
            }
            else
            {
                lengthField.setText("Length: ");
                frequencyField.setText("00000.0 Hz");
            }
        }
    }

    private ArrayList<String> getWavePathsAsList(TreeNode selectedFile)
    {
        ArrayList<String> wavePathsList = new ArrayList<String>();
        Enumeration e = selectedFile.children();
        while(e.hasMoreElements())
        {
            Object currentElement = e.nextElement();
            
            //If a soundfile has multiple possible wavefiles
            if (currentElement.toString().contains("\"rndwave\""))
            {
                Enumeration innerE = ((TreeNode)currentElement).children();
                while(innerE.hasMoreElements())
                {
                    Object currentInnerElement = innerE.nextElement();
                    if(currentInnerElement.toString().contains("\"wave\""))
                    {
                        //Maybe do some string massaging here before we just hand it back
                        wavePathsList.add(((TreeNode)currentInnerElement).toString());
                    }
                }
            }
            //If it only has one
            
            else if(currentElement.toString().contains("\"wave\""))
            {
                wavePathsList.add(((TreeNode)currentElement).toString());
            }
        }
        return wavePathsList;
    }

    private TreeNode getTreeNodeFromWavePath(String wavePath)
    {        
        VPKEntry scriptFile = getHeroScriptFile(((NamedHero) heroDropdown.getSelectedItem()).getInternalName());
        ScriptParser parser = new ScriptParser(new File(Paths.get(installDir + "\\dota\\" + scriptFile.getPath()).toString()));
        TreeModel model = parser.getTreeModel();
        
        TreeNode root = (TreeNode)model.getRoot();
        for(Enumeration e = ((DefaultMutableTreeNode)root).breadthFirstEnumeration(); e.hasMoreElements() && root != null;)
        {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) e.nextElement();
            if(node.toString().contains(wavePath))
            {
                return node;
            }
        }                       
        return null;
    }
}
